
name: Upload Python Package

on: 
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9.7'
    - name: Install Poetry
      uses: snok/install-poetry@v1.2.1
    - name: setup .gitconfig
      run: echo "1" > ./gitutor/.gitutor_config
    - name: Build and publish
      env: 
        passwordPy: ${{ secrets.PYPIKEY }}
      run: |
        poetry publish --username __token__ --password "$passwordPy" --build
